require File.join(File.dirname(__FILE__),'sponsor_list')
require File.join(File.dirname(__FILE__),'presentations08')
require File.join(File.dirname(__FILE__),'presentation')
require File.join(File.dirname(__FILE__),'email_message')
require File.join(File.dirname(__FILE__),'confirmation_email')
