---
:development: &defaults
  :adapter: postgresql
  :database: as2008_development
  :username: mahnve

:test:
  <<: *defaults
  :database: as2008_test

:production:
  <<: *defaults
  :database: as2008_production